# Generated by Django 5.1.3 on 2024-11-20 08:00

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'このメールアドレスは既に登録されています。'}, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='団体名')),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='代表者名')),
                ('booth_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ブース名')),
                ('booth_summary', models.TextField(blank=True, null=True, verbose_name='ブースの概要')),
                ('booth_description', models.TextField(blank=True, null=True, verbose_name='ブースの詳細情報')),
                ('full_name', models.CharField(max_length=255, verbose_name='氏名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('flyer_image', models.ImageField(upload_to=accounts.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='チラシ画像')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者')),
                ('email_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='UserActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'アクティベーショントークン',
                'verbose_name_plural': 'アクティベーショントークン',
            },
        ),
    ]
