# Generated by Django 5.1.3 on 2024-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivatetoken',
            name='extra_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
