# Generated by Django 5.1.3 on 2024-11-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='質問の内容を200文字以内で入力してください。', max_length=200, verbose_name='質問文')),
                ('question_type', models.CharField(choices=[('text', '一行テキスト'), ('textarea', '複数行テキスト'), ('radio', 'ラジオボタン'), ('checkbox', 'チェックボックス'), ('select', 'セレクトボックス')], default='text', max_length=20, verbose_name='質問タイプ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='アンケートのタイトルを200文字以内で入力してください。', max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(help_text='アンケートの詳細な説明を入力してください。', verbose_name='説明')),
                ('summary', models.TextField(help_text='アンケートの概要を500文字以内で入力してください。', max_length=500, verbose_name='概要')),
                ('start_date', models.DateTimeField(verbose_name='公開開始日時')),
                ('end_date', models.DateTimeField(verbose_name='公開終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アンケート',
                'verbose_name_plural': 'アンケート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='カテゴリー名を100文字以内で入力してください。', max_length=100, verbose_name='カテゴリー名')),
                ('description', models.TextField(blank=True, help_text='カテゴリーの説明を入力してください。', verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アンケートカテゴリー',
                'verbose_name_plural': 'アンケートカテゴリー',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='選択肢の内容を200文字以内で入力してください。', max_length=200, verbose_name='選択肢')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question', verbose_name='質問')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='アンケート'),
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='survey.surveycategory', verbose_name='カテゴリー'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='質問に対する回答を入力してください。', verbose_name='回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='質問')),
                ('choices', models.ManyToManyField(blank=True, related_name='answers', to='survey.questionchoice', verbose_name='選択された選択肢')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question')],
            },
        ),
    ]
